version: "3.9"  # optional since v1.27.0
services:
  web_api:
    build: ./src
    container_name: web_api_application
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  sql_server:
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        SA_PASSWORD: "#Password1234"
    container_name: sql_server2022
    ports:
      - "1439:1433"
    environment:
      ACCEPT_EULA: "Y"