services:
  sql_server:
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        SA_PASSWORD: "#Password1234"
    container_name: sql_server2022
    ports:
      - "1439:1433"
    environment:
      ACCEPT_EULA: "Y"